### ISSUE TITLE
Allow to use phantomjs from npm

### ISSUE THREAD

**Issue by btd** [juliangruber/capture-screenshot#1]
It looks a bit more convenient use npm version of phantomjs. 
Need just instead exec('phantomjs use 

```
var phantomjs = require('phantomjs')
var binPath = phantomjs.path

exec(binPath
```

Or something like this (i did not check).

Thanks

**Comment by juliangruber** [comment]
I was using the phantomjs npm version before with [review](https://github.com/juliangruber/review) but it was causing a lot of troubles, especially when new node versions were released, as it relies on some native modules.

I agree it would be nicer to use that, but meh, just had too bad of an experience.

**Comment by btd** [comment]
It is not required, but it can be optional like:

``` javascript
var  phantomJs;

try {
    phantomJs = require('phantomjs').path;
} catch(e) {
    phantomJs = 'phantomjs'
}
// ....
exec(phantomJs + ' ' + args.join(' '), opts, function (err, stdout) {
    fn(err, stdout && new Buffer(stdout, 'base64'));
  });
```

Or you strictly opposed? If yes, i will just fork.

**Comment by juliangruber** [comment]
uargh, optional dependencies, how do they even work :D
