### ISSUE TITLE
How to make screenshot.capture() synchronous ?

### ISSUE THREAD

**Issue by ball6847** [juliangruber/capture-screenshot#10]
I have list of urls and want to process them line by line, but by default url-to-screenshot process them asynchronously which highly resource consumed when all url being captured together at the same time (even hang my pc in my case).

is the any way to call capture() synchronously ?

**Comment by juliangruber** [comment]
if running all the screenshots processes in parallel is the problem, you can just run them in series.

use a module like https://github.com/feross/run-series to run them one after another.

this is better than just making this module synchronous, as the process can still do other things while the screenshot is being taken.

**Comment by ball6847** [comment]
Thank you.
