### ISSUE TITLE
when cant find website

### ISSUE THREAD

**Issue by alydgithub** [juliangruber/capture-screenshot#16]
Hello,
When a website can't be found
 example screenshot("http://www.dfdsafdsfdscascdasc12xc.com")
The program just hangs.
Is there a property or method that can be set to exit or throw error after certain time has passed trying to get the website.
The current timeout(3000) is only for waiting for site to load then get snapshot.
Thanks

**Comment by juliangruber** [comment]
thanks for reporting! published as 0.6.2
