### ISSUE TITLE
Running on ubuntu server, will I need to install an x server?

### ISSUE THREAD

**Issue by GNUGradyn** [juliangruber/capture-screenshot#19]
I'm creating a discord bot. One of its features is the ability to grab a screnshot from `http://jef.works/picture-quote-generator` and paste that in your current channel. The bot is running on an ubuntu server, but appears to be genorating white squares with question marks like[ this](https://gradyn.com/host/gcore/quotes/example.png)
note: this IS in my bot startup script, I copied and pasted it from a phantomjs thread due to another error it was throwing: `QT_QPA_PLATFORM=offscreen`

Code genorating these white squares:
 ```
 screenshot('http://jef.works/picture-quote-generator/')
  .width(800)
  .height(600)
  .capture(function(err, img) {
    if (err) throw err;
    file = Math.round((new Date()).getTime() / 1000);
    fs.writeFileSync('/var/www/html/host/gcore/quotes/'+file+'.png', img);
```

**Comment by GNUGradyn** [comment]
EDIT: launching with xvfb-run doesn't appear to work either

**Comment by juliangruber** [comment]
Thanks for reporting this. Maybe this will work:

```bash
$ sudo apt-get install xvfb # or equivalent
$ export DISPLAY=':99.0'
$ Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
$ # run your script
```

**Comment by juliangruber** [comment]
it does work for running electron headlessly, so it might work with phantomjs too :)

**Comment by GNUGradyn** [comment]
That didn't seem to work, however it works via the url-to-image modle, I think this modle might not be giving the website enough time to make AJAX requests.

**Comment by juliangruber** [comment]
you can configure that via this option: https://github.com/juliangruber/url-to-screenshot#screenshottimeouttimeout
