### ISSUE TITLE
any plans for adding a delay for JS powered websites?

### ISSUE THREAD

**Issue by obiwankenoobi** [juliangruber/capture-screenshot#23]
Great tool thanks for sharing! The only one that actually works for me. Anyway I tried to play a little with the source code but without much success so I asking here - There is any plans for adding some kind of delay support to make it work with JS powered websites? I tried to add [here](https://github.com/juliangruber/capture-chrome/blob/master/index.js#L22) something like `sleep 3s` to be executed after it loading the page but it was absolutely wrong lol

**Comment by juliangruber** [comment]
Hmm, if chrome doesn't support this option, there isn't much we can change on that browser I think.

Seems like we can refactor `capture-chrome` to use pupeteer, then it will support that: https://superuser.com/questions/1209741/how-to-take-a-screenshot-of-a-page-n-seconds-after-page-is-loaded-with-chrome-he

**Comment by juliangruber** [comment]
Do you think you could take a stab at that? :)

**Comment by obiwankenoobi** [comment]
sure! I just tried SSH clone your repo to modify it but seems like I done have the permission to do so - how can I make it work?

**Comment by juliangruber** [comment]
https://help.github.com/categories/bootcamp/ is your friend :)

**Comment by obiwankenoobi** [comment]
Awesome - just created a PR  (:

**Comment by juliangruber** [comment]
this works in chrome now, is that good enough for you @obiwankenoobi?

**Comment by obiwankenoobi** [comment]
@juliangruber yeah man (:
