### ISSUE TITLE
phantomjs params

### ISSUE THREAD

**Issue by Fabryprog** [juliangruber/capture-screenshot#4]
Hello,

i am using this module, how to use it using an additional phantomjs params?

I had a problem when try to download https site's screenshot.
I resolve it using this command: phantomjs --ssl-protocol=any ......
( http://stackoverflow.com/questions/12021578/phantomjs-failing-to-open-https-site )

**Comment by juliangruber** [comment]
hey @Fabryprog, we can add an option to the javascript api, like `.ssl('any')` and then pass that down to where the phantomjs process is created. do you think you can create a pull request for this?

**Comment by Fabryprog** [comment]
Ok thanks. 

i am adding pull request for this feature!

goodbye!
