### ISSUE TITLE
Hi great people, the example you gave is not working. 

### ISSUE THREAD

**Issue by nmsbane** [juliangruber/capture-screenshot#7]
I created a file, 'screenshot.js' which has the code given in the docs. 
From the command line when i run node screenshot.js, the command prompt hangs. 
Can u please help me?

**Comment by juliangruber** [comment]
do you have phantomjs installed and in your path?

**Comment by nmsbane** [comment]
yes, i do have phantomjs installed, from the command line, i can type phantomjs, and i get a repl. So i am pretty much sure its working

**Comment by juliangruber** [comment]
are you running phantomjs 2.0.0? if not, you should upgrade

**Comment by nmsbane** [comment]
i am not running 2.0.0, i will try updating it and will let u know :), thanks for your help
